package main

import (
	"flag"
	"fmt"
	"net/url"
	"os"
	"os/user"
	"path/filepath"

	"github.com/pquerna/otp/totp"
	qrcode "github.com/skip2/go-qrcode"
	"gopkg.in/yaml.v3"

	"websh/internal/config"
)

// runConfig is the first-run helper an ordinary user runs to create
// ~/.config/websh.yaml and enroll their OTP secret by scanning a QR code shown
// in the terminal. It needs no privileges.
func runConfig(args []string) {
	fs := flag.NewFlagSet("websh config", flag.ExitOnError)
	force := fs.Bool("regenerate", false, "generate a new OTP secret even if one already exists")
	fs.BoolVar(force, "regen", false, "alias for --regenerate")
	invert := fs.Bool("invert", false, "invert QR colors (use on a light-background terminal)")
	issuer := fs.String("issuer", "websh", "OTP issuer label shown in the authenticator app")
	fs.Usage = func() {
		fmt.Fprintln(os.Stderr, "Usage: websh config [--regenerate] [--invert]")
		fmt.Fprintln(os.Stderr, "First-time setup: creates ~/.config/websh.yaml and shows a TOTP QR code.")
		fs.PrintDefaults()
	}
	_ = fs.Parse(args)

	u, err := user.Current()
	if err != nil {
		fatalf("cannot determine current user: %v", err)
	}
	path := filepath.Join(u.HomeDir, ".config", "websh.yaml")
	host, _ := os.Hostname()
	account := u.Username
	if host != "" {
		account += "@" + host
	}

	cfg, existed := loadOrNew(path)

	needSecret := !existed || cfg.OTPSecret == "" || *force
	if needSecret {
		key, err := totp.Generate(totp.GenerateOpts{Issuer: *issuer, AccountName: account})
		if err != nil {
			fatalf("generate OTP secret: %v", err)
		}
		cfg.OTPSecret = key.Secret()
	}
	if len(cfg.Sessions) == 0 {
		cfg.Sessions = []config.SessionSpec{{ID: "local", Type: "local", Name: "本机"}}
	}

	// Persist when we created the file or changed the secret.
	if needSecret || !existed {
		if err := writeConfig(path, cfg); err != nil {
			fatalf("write %s: %v", path, err)
		}
	}

	uri := otpauthURI(*issuer, account, cfg.OTPSecret)
	q, err := qrcode.New(uri, qrcode.Low)
	if err != nil {
		fatalf("build QR: %v", err)
	}

	fmt.Println()
	if existed && !needSecret {
		fmt.Printf("配置已存在：%s\n（如需重置 OTP 密钥请加 --regenerate）\n\n", path)
	} else {
		fmt.Printf("已写入配置：%s\n\n", path)
	}
	fmt.Println("用 Google Authenticator / 任意 TOTP 应用扫描下面的二维码：")
	fmt.Println()
	fmt.Println(q.ToSmallString(*invert))
	fmt.Printf("账户:   %s\n", account)
	fmt.Printf("密钥:   %s   (无法扫码时手动输入)\n", cfg.OTPSecret)
	fmt.Printf("URI:    %s\n\n", uri)
	fmt.Println("登录时用：本机用户名 + 密码 + 该 App 显示的 6 位验证码。")
	if *invert {
		return
	}
	fmt.Println("（若二维码扫不出，浅色终端请改用 `websh config --invert`）")
}

func loadOrNew(path string) (*config.Config, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return &config.Config{}, false
	}
	var c config.Config
	if err := yaml.Unmarshal(data, &c); err != nil {
		fatalf("existing %s is not valid YAML: %v", path, err)
	}
	return &c, true
}

func writeConfig(path string, cfg *config.Config) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}
	header := "# websh user config — generated by `websh config`.\n" +
		"# Add SSH sessions under `sessions:` (see README / websh.example.yaml).\n"
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, append([]byte(header), body...), 0o600); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func otpauthURI(issuer, account, secret string) string {
	label := url.PathEscape(issuer + ":" + account)
	v := url.Values{}
	v.Set("secret", secret)
	v.Set("issuer", issuer)
	return "otpauth://totp/" + label + "?" + v.Encode()
}

func fatalf(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "websh config: "+format+"\n", a...)
	os.Exit(1)
}
